CREATE TABLE listings (
      ID INT NOT NULL AUTO_INCREMENT,  
      title VARCHAR(32) NOT NULL,  
      allText TEXT NOT NULL,
      dateCreated DATETIME DEFAULT CURRENT_TIMESTAMP,
      dateModified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      imageURL VARCHAR(2048),  
      published BOOL NOT NULL DEFAULT 0,
      authorID INT NOT NULL,
      breedName VARCHAR(1000) NOT NULL,
      centerID INT NOT NULL,
      PRIMARY KEY (ID),
      FOREIGN KEY (authorID) REFERENCES users (ID) ON DELETE CASCADE,
      FOREIGN KEY (breedName) REFERENCES breeds (breedName) ON DELETE CASCADE,
      FOREIGN KEY (centerID) REFERENCES centers (ID) ON DELETE CASCADE
);